// ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ========= Copyright 2026 @ Strukto.AI All Rights Reserved. =========

// Generated by scripts/gen_tz_abbrevs.py; do not edit by hand.
//
// The lettered abbreviations every tzdata zone has carried since 1970,
// keyed by UTC offset in seconds. This is what GNU date prints for `%Z`
// and what Python's zoneinfo renders; Intl only offers `GMT+8`, so the
// TypeScript `date` looks the abbreviation up here by the offset Intl
// does report. A zone tzdata names by its offset alone (`+08`, `-03`)
// has no row, and an offset with no row renders that way. A zone that
// carried two names at one offset keeps the later one.

export const TZ_ABBREVS: Readonly<Record<string, readonly (readonly [number, string])[]>> = {
  'Africa/Abidjan': [[0, 'GMT']],
  'Africa/Accra': [[0, 'GMT']],
  'Africa/Addis_Ababa': [[10800, 'EAT']],
  'Africa/Algiers': [
    [0, 'WET'],
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Africa/Asmara': [[10800, 'EAT']],
  'Africa/Asmera': [[10800, 'EAT']],
  'Africa/Bamako': [[0, 'GMT']],
  'Africa/Bangui': [[3600, 'WAT']],
  'Africa/Banjul': [[0, 'GMT']],
  'Africa/Bissau': [[0, 'GMT']],
  'Africa/Blantyre': [[7200, 'CAT']],
  'Africa/Brazzaville': [[3600, 'WAT']],
  'Africa/Bujumbura': [[7200, 'CAT']],
  'Africa/Cairo': [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  'Africa/Ceuta': [
    [0, 'WET'],
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Africa/Conakry': [[0, 'GMT']],
  'Africa/Dakar': [[0, 'GMT']],
  'Africa/Dar_es_Salaam': [[10800, 'EAT']],
  'Africa/Djibouti': [[10800, 'EAT']],
  'Africa/Douala': [[3600, 'WAT']],
  'Africa/Freetown': [[0, 'GMT']],
  'Africa/Gaborone': [[7200, 'CAT']],
  'Africa/Harare': [[7200, 'CAT']],
  'Africa/Johannesburg': [[7200, 'SAST']],
  'Africa/Juba': [
    [7200, 'CAT'],
    [10800, 'EAT'],
  ],
  'Africa/Kampala': [[10800, 'EAT']],
  'Africa/Khartoum': [
    [7200, 'CAT'],
    [10800, 'EAT'],
  ],
  'Africa/Kigali': [[7200, 'CAT']],
  'Africa/Kinshasa': [[3600, 'WAT']],
  'Africa/Lagos': [[3600, 'WAT']],
  'Africa/Libreville': [[3600, 'WAT']],
  'Africa/Lome': [[0, 'GMT']],
  'Africa/Luanda': [[3600, 'WAT']],
  'Africa/Lubumbashi': [[7200, 'CAT']],
  'Africa/Lusaka': [[7200, 'CAT']],
  'Africa/Malabo': [[3600, 'WAT']],
  'Africa/Maputo': [[7200, 'CAT']],
  'Africa/Maseru': [[7200, 'SAST']],
  'Africa/Mbabane': [[7200, 'SAST']],
  'Africa/Mogadishu': [[10800, 'EAT']],
  'Africa/Monrovia': [
    [-2670, 'MMT'],
    [0, 'GMT'],
  ],
  'Africa/Nairobi': [[10800, 'EAT']],
  'Africa/Ndjamena': [
    [3600, 'WAT'],
    [7200, 'WAST'],
  ],
  'Africa/Niamey': [[3600, 'WAT']],
  'Africa/Nouakchott': [[0, 'GMT']],
  'Africa/Ouagadougou': [[0, 'GMT']],
  'Africa/Porto-Novo': [[3600, 'WAT']],
  'Africa/Sao_Tome': [
    [0, 'GMT'],
    [3600, 'WAT'],
  ],
  'Africa/Timbuktu': [[0, 'GMT']],
  'Africa/Tripoli': [
    [3600, 'CET'],
    [7200, 'EET'],
  ],
  'Africa/Tunis': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Africa/Windhoek': [
    [3600, 'WAT'],
    [7200, 'CAT'],
  ],
  'America/Adak': [
    [-39600, 'BST'],
    [-36000, 'HST'],
    [-32400, 'HDT'],
  ],
  'America/Anchorage': [
    [-36000, 'AHST'],
    [-32400, 'AKST'],
    [-28800, 'AKDT'],
  ],
  'America/Anguilla': [[-14400, 'AST']],
  'America/Antigua': [[-14400, 'AST']],
  'America/Aruba': [[-14400, 'AST']],
  'America/Atikokan': [[-18000, 'EST']],
  'America/Atka': [
    [-39600, 'BST'],
    [-36000, 'HST'],
    [-32400, 'HDT'],
  ],
  'America/Bahia_Banderas': [
    [-25200, 'MST'],
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Barbados': [
    [-14400, 'AST'],
    [-10800, 'ADT'],
  ],
  'America/Belize': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Blanc-Sablon': [[-14400, 'AST']],
  'America/Boise': [
    [-25200, 'MST'],
    [-21600, 'MDT'],
  ],
  'America/Cambridge_Bay': [
    [-25200, 'MST'],
    [-21600, 'MDT'],
    [-18000, 'EST'],
  ],
  'America/Cancun': [
    [-21600, 'CST'],
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Cayman': [[-18000, 'EST']],
  'America/Chicago': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Chihuahua': [
    [-25200, 'MST'],
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Ciudad_Juarez': [
    [-25200, 'MST'],
    [-21600, 'MDT'],
    [-18000, 'CDT'],
  ],
  'America/Coral_Harbour': [[-18000, 'EST']],
  'America/Costa_Rica': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Creston': [[-25200, 'MST']],
  'America/Curacao': [[-14400, 'AST']],
  'America/Danmarkshavn': [[0, 'GMT']],
  'America/Dawson': [
    [-32400, 'YST'],
    [-28800, 'PST'],
    [-25200, 'MST'],
  ],
  'America/Dawson_Creek': [
    [-28800, 'PST'],
    [-25200, 'MST'],
  ],
  'America/Denver': [
    [-25200, 'MST'],
    [-21600, 'MDT'],
  ],
  'America/Detroit': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Dominica': [[-14400, 'AST']],
  'America/Edmonton': [
    [-25200, 'MST'],
    [-21600, 'CST'],
  ],
  'America/El_Salvador': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Ensenada': [
    [-28800, 'PST'],
    [-25200, 'PDT'],
  ],
  'America/Fort_Nelson': [
    [-28800, 'PST'],
    [-25200, 'MST'],
  ],
  'America/Fort_Wayne': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Glace_Bay': [
    [-14400, 'AST'],
    [-10800, 'ADT'],
  ],
  'America/Goose_Bay': [
    [-14400, 'AST'],
    [-10800, 'ADT'],
    [-7200, 'ADDT'],
  ],
  'America/Grand_Turk': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Grenada': [[-14400, 'AST']],
  'America/Guadeloupe': [[-14400, 'AST']],
  'America/Guatemala': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Halifax': [
    [-14400, 'AST'],
    [-10800, 'ADT'],
  ],
  'America/Havana': [
    [-18000, 'CST'],
    [-14400, 'CDT'],
  ],
  'America/Hermosillo': [
    [-25200, 'MST'],
    [-21600, 'MDT'],
  ],
  'America/Indiana/Indianapolis': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Indiana/Knox': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Indiana/Marengo': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Indiana/Petersburg': [
    [-21600, 'CST'],
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Indiana/Tell_City': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
    [-14400, 'EDT'],
  ],
  'America/Indiana/Vevay': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Indiana/Vincennes': [
    [-21600, 'CST'],
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Indiana/Winamac': [
    [-21600, 'CST'],
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Indianapolis': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Inuvik': [
    [-28800, 'PST'],
    [-25200, 'MST'],
    [-21600, 'MDT'],
  ],
  'America/Iqaluit': [
    [-21600, 'CST'],
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Jamaica': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Juneau': [
    [-32400, 'AKST'],
    [-28800, 'AKDT'],
    [-25200, 'PDT'],
  ],
  'America/Kentucky/Louisville': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Kentucky/Monticello': [
    [-21600, 'CST'],
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Knox_IN': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Kralendijk': [[-14400, 'AST']],
  'America/Los_Angeles': [
    [-28800, 'PST'],
    [-25200, 'PDT'],
  ],
  'America/Louisville': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Lower_Princes': [[-14400, 'AST']],
  'America/Managua': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Marigot': [[-14400, 'AST']],
  'America/Martinique': [
    [-14400, 'AST'],
    [-10800, 'ADT'],
  ],
  'America/Matamoros': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Mazatlan': [
    [-25200, 'MST'],
    [-21600, 'MDT'],
  ],
  'America/Menominee': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Merida': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Metlakatla': [
    [-32400, 'AKST'],
    [-28800, 'AKDT'],
    [-25200, 'PDT'],
  ],
  'America/Mexico_City': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Miquelon': [[-14400, 'AST']],
  'America/Moncton': [
    [-14400, 'AST'],
    [-10800, 'ADT'],
  ],
  'America/Monterrey': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Montreal': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Montserrat': [[-14400, 'AST']],
  'America/Nassau': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/New_York': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Nipigon': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Nome': [
    [-39600, 'BST'],
    [-36000, 'BDT'],
    [-32400, 'AKST'],
    [-28800, 'AKDT'],
  ],
  'America/North_Dakota/Beulah': [
    [-25200, 'MST'],
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/North_Dakota/Center': [
    [-25200, 'MST'],
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/North_Dakota/New_Salem': [
    [-25200, 'MST'],
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Ojinaga': [
    [-25200, 'MST'],
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Panama': [[-18000, 'EST']],
  'America/Pangnirtung': [
    [-21600, 'CST'],
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Phoenix': [[-25200, 'MST']],
  'America/Port-au-Prince': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Port_of_Spain': [[-14400, 'AST']],
  'America/Puerto_Rico': [[-14400, 'AST']],
  'America/Rainy_River': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Rankin_Inlet': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Regina': [[-21600, 'CST']],
  'America/Resolute': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Santa_Isabel': [
    [-28800, 'PST'],
    [-25200, 'PDT'],
  ],
  'America/Santo_Domingo': [
    [-18000, 'EST'],
    [-14400, 'AST'],
  ],
  'America/Shiprock': [
    [-25200, 'MST'],
    [-21600, 'MDT'],
  ],
  'America/Sitka': [
    [-32400, 'AKST'],
    [-28800, 'AKDT'],
    [-25200, 'PDT'],
  ],
  'America/St_Barthelemy': [[-14400, 'AST']],
  'America/St_Johns': [
    [-12600, 'NST'],
    [-9000, 'NDT'],
    [-5400, 'NDDT'],
  ],
  'America/St_Kitts': [[-14400, 'AST']],
  'America/St_Lucia': [[-14400, 'AST']],
  'America/St_Thomas': [[-14400, 'AST']],
  'America/St_Vincent': [[-14400, 'AST']],
  'America/Swift_Current': [
    [-25200, 'MST'],
    [-21600, 'CST'],
  ],
  'America/Tegucigalpa': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Thule': [
    [-14400, 'AST'],
    [-10800, 'ADT'],
  ],
  'America/Thunder_Bay': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Tijuana': [
    [-28800, 'PST'],
    [-25200, 'PDT'],
  ],
  'America/Toronto': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'America/Tortola': [[-14400, 'AST']],
  'America/Vancouver': [
    [-28800, 'PST'],
    [-25200, 'MST'],
  ],
  'America/Virgin': [[-14400, 'AST']],
  'America/Whitehorse': [
    [-28800, 'PST'],
    [-25200, 'MST'],
  ],
  'America/Winnipeg': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'America/Yakutat': [
    [-32400, 'AKST'],
    [-28800, 'AKDT'],
  ],
  'America/Yellowknife': [
    [-25200, 'MST'],
    [-21600, 'CST'],
  ],
  'Antarctica/Macquarie': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Antarctica/McMurdo': [
    [43200, 'NZST'],
    [46800, 'NZDT'],
  ],
  'Antarctica/Rothera': [[0, '-00']],
  'Antarctica/South_Pole': [
    [43200, 'NZST'],
    [46800, 'NZDT'],
  ],
  'Antarctica/Vostok': [[0, '-00']],
  'Arctic/Longyearbyen': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Asia/Amman': [[7200, 'EET']],
  'Asia/Beirut': [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  'Asia/Calcutta': [[19800, 'IST']],
  'Asia/Chongqing': [
    [28800, 'CST'],
    [32400, 'CDT'],
  ],
  'Asia/Chungking': [
    [28800, 'CST'],
    [32400, 'CDT'],
  ],
  'Asia/Damascus': [[7200, 'EET']],
  'Asia/Famagusta': [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  'Asia/Gaza': [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  'Asia/Harbin': [
    [28800, 'CST'],
    [32400, 'CDT'],
  ],
  'Asia/Hebron': [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  'Asia/Hong_Kong': [
    [28800, 'HKT'],
    [32400, 'HKST'],
  ],
  'Asia/Istanbul': [[7200, 'EET']],
  'Asia/Jakarta': [[25200, 'WIB']],
  'Asia/Jayapura': [[32400, 'WIT']],
  'Asia/Jerusalem': [
    [7200, 'IST'],
    [10800, 'IDT'],
  ],
  'Asia/Karachi': [
    [18000, 'PKT'],
    [21600, 'PKST'],
  ],
  'Asia/Kolkata': [[19800, 'IST']],
  'Asia/Macao': [
    [28800, 'CST'],
    [32400, 'CDT'],
  ],
  'Asia/Macau': [
    [28800, 'CST'],
    [32400, 'CDT'],
  ],
  'Asia/Makassar': [[28800, 'WITA']],
  'Asia/Manila': [
    [28800, 'PST'],
    [32400, 'PDT'],
  ],
  'Asia/Nicosia': [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  'Asia/Pontianak': [
    [25200, 'WIB'],
    [28800, 'WITA'],
  ],
  'Asia/Pyongyang': [
    [30600, 'KST'],
    [32400, 'KST'],
  ],
  'Asia/Seoul': [
    [32400, 'KST'],
    [36000, 'KDT'],
  ],
  'Asia/Shanghai': [
    [28800, 'CST'],
    [32400, 'CDT'],
  ],
  'Asia/Taipei': [
    [28800, 'CST'],
    [32400, 'CDT'],
  ],
  'Asia/Tel_Aviv': [
    [7200, 'IST'],
    [10800, 'IDT'],
  ],
  'Asia/Tokyo': [[32400, 'JST']],
  'Asia/Ujung_Pandang': [[28800, 'WITA']],
  'Atlantic/Azores': [[3600, 'WEST']],
  'Atlantic/Bermuda': [
    [-14400, 'AST'],
    [-10800, 'ADT'],
  ],
  'Atlantic/Canary': [
    [0, 'WET'],
    [3600, 'WEST'],
  ],
  'Atlantic/Faeroe': [
    [0, 'WET'],
    [3600, 'WEST'],
  ],
  'Atlantic/Faroe': [
    [0, 'WET'],
    [3600, 'WEST'],
  ],
  'Atlantic/Jan_Mayen': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Atlantic/Madeira': [
    [0, 'WET'],
    [3600, 'WEST'],
  ],
  'Atlantic/Reykjavik': [[0, 'GMT']],
  'Atlantic/St_Helena': [[0, 'GMT']],
  'Australia/ACT': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Australia/Adelaide': [
    [34200, 'ACST'],
    [37800, 'ACDT'],
  ],
  'Australia/Brisbane': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Australia/Broken_Hill': [
    [34200, 'ACST'],
    [37800, 'ACDT'],
  ],
  'Australia/Canberra': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Australia/Currie': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Australia/Darwin': [[34200, 'ACST']],
  'Australia/Hobart': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Australia/LHI': [[36000, 'AEST']],
  'Australia/Lindeman': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Australia/Lord_Howe': [[36000, 'AEST']],
  'Australia/Melbourne': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Australia/NSW': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Australia/North': [[34200, 'ACST']],
  'Australia/Perth': [
    [28800, 'AWST'],
    [32400, 'AWDT'],
  ],
  'Australia/Queensland': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Australia/South': [
    [34200, 'ACST'],
    [37800, 'ACDT'],
  ],
  'Australia/Sydney': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Australia/Tasmania': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Australia/Victoria': [
    [36000, 'AEST'],
    [39600, 'AEDT'],
  ],
  'Australia/West': [
    [28800, 'AWST'],
    [32400, 'AWDT'],
  ],
  'Australia/Yancowinna': [
    [34200, 'ACST'],
    [37800, 'ACDT'],
  ],
  CET: [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  CST6CDT: [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'Canada/Atlantic': [
    [-14400, 'AST'],
    [-10800, 'ADT'],
  ],
  'Canada/Central': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'Canada/Eastern': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'Canada/Mountain': [
    [-25200, 'MST'],
    [-21600, 'CST'],
  ],
  'Canada/Newfoundland': [
    [-12600, 'NST'],
    [-9000, 'NDT'],
    [-5400, 'NDDT'],
  ],
  'Canada/Pacific': [
    [-28800, 'PST'],
    [-25200, 'MST'],
  ],
  'Canada/Saskatchewan': [[-21600, 'CST']],
  'Canada/Yukon': [
    [-28800, 'PST'],
    [-25200, 'MST'],
  ],
  Cuba: [
    [-18000, 'CST'],
    [-14400, 'CDT'],
  ],
  EET: [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  EST: [[-18000, 'EST']],
  EST5EDT: [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  Egypt: [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  Eire: [
    [0, 'GMT'],
    [3600, 'IST'],
  ],
  'Etc/GMT': [[0, 'GMT']],
  'Etc/GMT+0': [[0, 'GMT']],
  'Etc/GMT-0': [[0, 'GMT']],
  'Etc/GMT0': [[0, 'GMT']],
  'Etc/Greenwich': [[0, 'GMT']],
  'Etc/UCT': [[0, 'UTC']],
  'Etc/UTC': [[0, 'UTC']],
  'Etc/Universal': [[0, 'UTC']],
  'Etc/Zulu': [[0, 'UTC']],
  'Europe/Amsterdam': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Andorra': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Athens': [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  'Europe/Belfast': [
    [0, 'GMT'],
    [3600, 'BST'],
  ],
  'Europe/Belgrade': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Berlin': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Bratislava': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Brussels': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Bucharest': [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  'Europe/Budapest': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Busingen': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Chisinau': [
    [7200, 'EET'],
    [10800, 'EEST'],
    [14400, 'MSD'],
  ],
  'Europe/Copenhagen': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Dublin': [
    [0, 'GMT'],
    [3600, 'IST'],
  ],
  'Europe/Gibraltar': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Guernsey': [
    [0, 'GMT'],
    [3600, 'BST'],
  ],
  'Europe/Helsinki': [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  'Europe/Isle_of_Man': [
    [0, 'GMT'],
    [3600, 'BST'],
  ],
  'Europe/Istanbul': [[7200, 'EET']],
  'Europe/Jersey': [
    [0, 'GMT'],
    [3600, 'BST'],
  ],
  'Europe/Kaliningrad': [
    [7200, 'EET'],
    [14400, 'MSD'],
  ],
  'Europe/Kiev': [
    [7200, 'EET'],
    [10800, 'EEST'],
    [14400, 'MSD'],
  ],
  'Europe/Kirov': [
    [10800, 'MSK'],
    [14400, 'MSK'],
  ],
  'Europe/Kyiv': [
    [7200, 'EET'],
    [10800, 'EEST'],
    [14400, 'MSD'],
  ],
  'Europe/Lisbon': [
    [0, 'WET'],
    [3600, 'WEST'],
    [7200, 'CEST'],
  ],
  'Europe/Ljubljana': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/London': [
    [0, 'GMT'],
    [3600, 'BST'],
  ],
  'Europe/Luxembourg': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Madrid': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Malta': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Mariehamn': [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  'Europe/Minsk': [
    [7200, 'EET'],
    [14400, 'MSD'],
  ],
  'Europe/Monaco': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Moscow': [
    [7200, 'EET'],
    [10800, 'MSK'],
    [14400, 'MSK'],
  ],
  'Europe/Nicosia': [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  'Europe/Oslo': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Paris': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Podgorica': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Prague': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Riga': [
    [7200, 'EET'],
    [10800, 'EEST'],
    [14400, 'MSD'],
  ],
  'Europe/Rome': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/San_Marino': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Sarajevo': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Simferopol': [
    [7200, 'EET'],
    [10800, 'MSK'],
    [14400, 'MSK'],
  ],
  'Europe/Skopje': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Sofia': [
    [7200, 'EET'],
    [10800, 'EEST'],
  ],
  'Europe/Stockholm': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Tallinn': [
    [7200, 'EET'],
    [10800, 'EEST'],
    [14400, 'MSD'],
  ],
  'Europe/Tirane': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Tiraspol': [
    [7200, 'EET'],
    [10800, 'EEST'],
    [14400, 'MSD'],
  ],
  'Europe/Uzhgorod': [
    [7200, 'EET'],
    [10800, 'EEST'],
    [14400, 'MSD'],
  ],
  'Europe/Vaduz': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Vatican': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Vienna': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Vilnius': [
    [3600, 'CET'],
    [7200, 'EET'],
    [10800, 'EEST'],
    [14400, 'MSD'],
  ],
  'Europe/Volgograd': [[10800, 'MSK']],
  'Europe/Warsaw': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Zagreb': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  'Europe/Zaporozhye': [
    [7200, 'EET'],
    [10800, 'EEST'],
    [14400, 'MSD'],
  ],
  'Europe/Zurich': [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  Factory: [[0, '-00']],
  GB: [
    [0, 'GMT'],
    [3600, 'BST'],
  ],
  'GB-Eire': [
    [0, 'GMT'],
    [3600, 'BST'],
  ],
  GMT: [[0, 'GMT']],
  'GMT+0': [[0, 'GMT']],
  'GMT-0': [[0, 'GMT']],
  GMT0: [[0, 'GMT']],
  Greenwich: [[0, 'GMT']],
  HST: [[-36000, 'HST']],
  Hongkong: [
    [28800, 'HKT'],
    [32400, 'HKST'],
  ],
  Iceland: [[0, 'GMT']],
  'Indian/Antananarivo': [[10800, 'EAT']],
  'Indian/Comoro': [[10800, 'EAT']],
  'Indian/Mayotte': [[10800, 'EAT']],
  Israel: [
    [7200, 'IST'],
    [10800, 'IDT'],
  ],
  Jamaica: [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  Japan: [[32400, 'JST']],
  Libya: [
    [3600, 'CET'],
    [7200, 'EET'],
  ],
  MET: [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  MST: [[-25200, 'MST']],
  MST7MDT: [
    [-25200, 'MST'],
    [-21600, 'MDT'],
  ],
  'Mexico/BajaNorte': [
    [-28800, 'PST'],
    [-25200, 'PDT'],
  ],
  'Mexico/BajaSur': [
    [-25200, 'MST'],
    [-21600, 'MDT'],
  ],
  'Mexico/General': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  NZ: [
    [43200, 'NZST'],
    [46800, 'NZDT'],
  ],
  Navajo: [
    [-25200, 'MST'],
    [-21600, 'MDT'],
  ],
  PRC: [
    [28800, 'CST'],
    [32400, 'CDT'],
  ],
  PST8PDT: [
    [-28800, 'PST'],
    [-25200, 'PDT'],
  ],
  'Pacific/Auckland': [
    [43200, 'NZST'],
    [46800, 'NZDT'],
  ],
  'Pacific/Guam': [
    [36000, 'ChST'],
    [39600, 'GDT'],
  ],
  'Pacific/Honolulu': [[-36000, 'HST']],
  'Pacific/Johnston': [[-36000, 'HST']],
  'Pacific/Midway': [[-39600, 'SST']],
  'Pacific/Pago_Pago': [[-39600, 'SST']],
  'Pacific/Saipan': [
    [36000, 'ChST'],
    [39600, 'GDT'],
  ],
  'Pacific/Samoa': [[-39600, 'SST']],
  Poland: [
    [3600, 'CET'],
    [7200, 'CEST'],
  ],
  Portugal: [
    [0, 'WET'],
    [3600, 'WEST'],
    [7200, 'CEST'],
  ],
  ROC: [
    [28800, 'CST'],
    [32400, 'CDT'],
  ],
  ROK: [
    [32400, 'KST'],
    [36000, 'KDT'],
  ],
  Turkey: [[7200, 'EET']],
  UCT: [[0, 'UTC']],
  'US/Alaska': [
    [-36000, 'AHST'],
    [-32400, 'AKST'],
    [-28800, 'AKDT'],
  ],
  'US/Aleutian': [
    [-39600, 'BST'],
    [-36000, 'HST'],
    [-32400, 'HDT'],
  ],
  'US/Arizona': [[-25200, 'MST']],
  'US/Central': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'US/East-Indiana': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'US/Eastern': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'US/Hawaii': [[-36000, 'HST']],
  'US/Indiana-Starke': [
    [-21600, 'CST'],
    [-18000, 'CDT'],
  ],
  'US/Michigan': [
    [-18000, 'EST'],
    [-14400, 'EDT'],
  ],
  'US/Mountain': [
    [-25200, 'MST'],
    [-21600, 'MDT'],
  ],
  'US/Pacific': [
    [-28800, 'PST'],
    [-25200, 'PDT'],
  ],
  'US/Samoa': [[-39600, 'SST']],
  UTC: [[0, 'UTC']],
  Universal: [[0, 'UTC']],
  'W-SU': [
    [7200, 'EET'],
    [10800, 'MSK'],
    [14400, 'MSK'],
  ],
  WET: [
    [0, 'WET'],
    [3600, 'WEST'],
    [7200, 'CEST'],
  ],
  Zulu: [[0, 'UTC']],
}
